/**
 * Do not edit this file!
 */
import { products } from "./data"

const sleep = async (ms) => {
  return new Promise((resolve, reject) =>
    setTimeout(() => {
      if (Math.random() > 0.1) {
        resolve()
      } else {
        reject()
      }
    }, ms),
  )
}

export const getProducts = async (pageNumber = undefined, pageSize = undefined) => {
  if (pageNumber === undefined || pageSize === undefined) {
    await sleep(50 * products.length)
    return products
  } else {
    await sleep(50 * pageSize)
    return products.slice((pageNumber - 1) * pageSize, pageNumber * pageSize)
  }
}
