/**
 * Do not edit this file!
 */
import allure from "../assets/products/allure.jpg"
import bliss from "../assets/products/bliss.jpg"
import bloom from "../assets/products/bloom.jpg"
import brightness from "../assets/products/brightness.jpg"
import brilliance from "../assets/products/brilliance.jpg"
import calm from "../assets/products/calm.jpg"
import care from "../assets/products/care.jpg"
import charm from "../assets/products/charm.jpg"
import comfort from "../assets/products/comfort.jpg"
import delectation from "../assets/products/delectation.jpg"
import delicacy from "../assets/products/delicacy.jpg"
import delight from "../assets/products/delight.jpg"
import dream from "../assets/products/dream.jpg"
import elation from "../assets/products/elation.jpg"
import elegance from "../assets/products/elegance.jpg"
import euphoria from "../assets/products/euphoria.jpg"
import exuberance from "../assets/products/exuberance.jpg"
import felicity from "../assets/products/felicity.jpg"
import fragrance from "../assets/products/fragrance.jpg"
import freshness from "../assets/products/freshness.jpg"
import glamour from "../assets/products/glamour.jpg"
import glory from "../assets/products/glory.jpg"
import glow from "../assets/products/glow.jpg"
import grace from "../assets/products/grace.jpg"
import harmony from "../assets/products/harmony.jpg"
import idyll from "../assets/products/idyll.jpg"
import joy from "../assets/products/joy.jpg"
import jubilation from "../assets/products/jubilation.jpg"
import luminosity from "../assets/products/luminosity.jpg"
import lusciousness from "../assets/products/lusciousness.jpg"
import lustre from "../assets/products/lustre.jpg"
import luxury from "../assets/products/luxury.jpg"
import magnificence from "../assets/products/magnificence.jpg"
import majesty from "../assets/products/majesty.jpg"
import opulence from "../assets/products/opulence.jpg"
import paradise from "../assets/products/paradise.jpg"
import peace from "../assets/products/peace.jpg"
import poise from "../assets/products/poise.jpg"
import radiance from "../assets/products/radiance.jpg"
import redolence from "../assets/products/redolence.jpg"
import relaxation from "../assets/products/relaxation.jpg"
import resplendence from "../assets/products/resplendence.jpg"
import sensuousness from "../assets/products/sensuousness.jpg"
import serenity from "../assets/products/serenity.jpg"
import shine from "../assets/products/shine.jpg"
import simplicity from "../assets/products/simplicity.jpg"
import sophistication from "../assets/products/sophistication.jpg"
import splendour from "../assets/products/splendour.jpg"
import tranquility from "../assets/products/tranquility.jpg"
import treasure from "../assets/products/treasure.jpg"

export const products = [
  {
    name: "peace",
    image: peace,
    price: 19.99,
  },
  {
    name: "freshness",
    image: freshness,
    price: 24.99,
  },
  {
    name: "harmony",
    image: harmony,
    price: 34.99,
  },
  {
    name: "poise",
    image: poise,
    price: 24.99,
    position: "bottom",
  },
  {
    name: "elegance",
    image: elegance,
    price: 19.99,
  },
  {
    name: "lustre",
    image: lustre,
    price: 39.99,
  },
  {
    name: "bliss",
    image: bliss,
    price: 29.99,
  },
  {
    name: "charm",
    image: charm,
    price: 19.99,
  },
  {
    name: "brightness",
    image: brightness,
    price: 24.99,
  },
  {
    name: "radiance",
    image: radiance,
    price: 19.99,
  },
  {
    name: "bloom",
    image: bloom,
    price: 19.99,
  },
  {
    name: "allure",
    image: allure,
    price: 29.99,
  },
  {
    name: "shine",
    image: shine,
    price: 19.99,
  },
  {
    name: "resplendence",
    image: resplendence,
    price: 34.99,
  },
  {
    name: "delicacy",
    image: delicacy,
    price: 24.99,
  },
  {
    name: "idyll",
    image: idyll,
    price: 24.99,
  },
  {
    name: "dream",
    image: dream,
    price: 19.99,
  },
  {
    name: "brilliance",
    image: brilliance,
    price: 29.99,
    position: "top",
  },
  {
    name: "care",
    image: care,
    price: 19.99,
  },
  {
    name: "delight",
    image: delight,
    price: 29.99,
  },
  {
    name: "grace",
    image: grace,
    price: 34.99,
  },
  {
    name: "majesty",
    image: majesty,
    price: 34.99,
  },
  {
    name: "serenity",
    image: serenity,
    price: 24.99,
  },
  {
    name: "calm",
    image: calm,
    price: 19.99,
  },
  {
    name: "opulence",
    image: opulence,
    price: 34.99,
  },
  {
    name: "treasure",
    image: treasure,
    price: 29.99,
  },
  {
    name: "splendour",
    image: splendour,
    price: 34.99,
  },
  {
    name: "sophistication",
    image: sophistication,
    price: 24.99,
  },
  {
    name: "joy",
    image: joy,
    price: 24.99,
  },
  {
    name: "glamour",
    image: glamour,
    price: 29.99,
  },
  {
    name: "tranquility",
    image: tranquility,
    price: 19.99,
  },
  {
    name: "luminosity",
    image: luminosity,
    price: 29.99,
  },
  {
    name: "felicity",
    image: felicity,
    price: 24.99,
  },
  {
    name: "redolence",
    image: redolence,
    price: 29.99,
  },
  {
    name: "euphoria",
    image: euphoria,
    price: 34.99,
  },
  {
    name: "comfort",
    image: comfort,
    price: 24.99,
  },
  {
    name: "luxury",
    image: luxury,
    price: 39.99,
  },
  {
    name: "jubilation",
    image: jubilation,
    price: 24.99,
  },
  {
    name: "magnificence",
    image: magnificence,
    price: 24.99,
  },
  {
    name: "glory",
    image: glory,
    price: 29.99,
  },
  {
    name: "lusciousness",
    image: lusciousness,
    price: 19.99,
  },
  {
    name: "glow",
    image: glow,
    price: 19.99,
    position: "bottom",
  },
  {
    name: "exuberance",
    image: exuberance,
    price: 29.99,
    position: "top",
  },
  {
    name: "simplicity",
    image: simplicity,
    price: 19.99,
    position: "bottom",
  },
  {
    name: "paradise",
    image: paradise,
    price: 34.99,
  },
  {
    name: "elation",
    image: elation,
    price: 24.99,
  },
  {
    name: "delectation",
    image: delectation,
    price: 19.99,
  },
  {
    name: "fragrance",
    image: fragrance,
    price: 29.99,
  },
  {
    name: "sensuousness",
    image: sensuousness,
    price: 34.99,
    position: "top",
  },
  {
    name: "relaxation",
    image: relaxation,
    price: 24.99,
  },
]
